### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ondrovic** [ematsakov/highlight#6]
Is there anyway you could add a raw option that still formats it, but opens the code into a new blank window?

**Comment by owenBeresford** [comment]
Isn't the new window idea abit off scope for a highlighter?  
Try something like http://slickmedia.co.uk/blog/jquery-open-link-class-new-window/

Or you could make a new webpage, with the  current highlighter.

**Comment by ematsakov** [comment]
Hi, there!
Yes, opening new window with a code is not related to highlighter plugin functionality.
It's possible to do separately with `window.open("http://www.example.com");` code. And place highlighter functionality on the page you opening.
Thanks,
Evgeny
